In [1]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
# Importing the datset
dataset = pd.read_csv('creditcard.csv')
x = dataset.iloc[:,1:30].values
y = dataset.iloc[:,30].values

In [23]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [24]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

### Selecting all features

In [5]:
# Applying PCA for Feature Extraction
from sklearn.decomposition import PCA
pca = PCA(n_components = None)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.06780684, 0.03608768, 0.0357645 , 0.0352035 , 0.03505041,
       0.03492344, 0.03487712, 0.03482044, 0.03474247, 0.03471081,
       0.03468741, 0.03465127, 0.03463101, 0.03457837, 0.03456009,
       0.03451579, 0.03449614, 0.03446875, 0.03439284, 0.03437869,
       0.03434884, 0.03433792, 0.03431657, 0.03427221, 0.03410772,
       0.03362036, 0.03287469, 0.0313348 , 0.0014393 ])

In [6]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

# Results in form of Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[55395,  1466],
       [   14,    87]], dtype=int64)

### Selecting 5 features

In [10]:
# Applying PCA for Feature Extraction
from sklearn.decomposition import PCA
pca = PCA(n_components = 5)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.06776166, 0.03564796, 0.03515886, 0.03491779, 0.03477336])

In [11]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

# Results in form of Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[55881,   980],
       [   69,    32]], dtype=int64)

### Selecting 10 features

In [15]:
# Applying PCA for Feature Extraction
from sklearn.decomposition import PCA
pca = PCA(n_components = 10)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.06776029, 0.03576378, 0.03540425, 0.03493825, 0.03486436,
       0.03482441, 0.03476446, 0.03470221, 0.03465486, 0.03463185])

In [16]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

# Results in form of Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[55593,  1268],
       [   47,    54]], dtype=int64)

### Selecting 15 features

In [20]:
# Applying PCA for Feature Extraction
from sklearn.decomposition import PCA
pca = PCA(n_components = 15)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.06780558, 0.03603688, 0.03573174, 0.03519002, 0.03496459,
       0.03492044, 0.0347843 , 0.03472723, 0.03469333, 0.03466709,
       0.03464027, 0.03461597, 0.03455585, 0.03453625, 0.0345111 ])

In [21]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

# Results in form of Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[55641,  1220],
       [   38,    63]], dtype=int64)

### Selecting 20 features

In [25]:
# Applying PCA for Feature Extraction
from sklearn.decomposition import PCA
pca = PCA(n_components = 20)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.06780684, 0.03608768, 0.0357645 , 0.0352035 , 0.03505041,
       0.03492344, 0.03487712, 0.03482044, 0.03474247, 0.03471081,
       0.03468741, 0.03465127, 0.03463101, 0.03457837, 0.03456009,
       0.03451579, 0.03449614, 0.03446875, 0.03439284, 0.03437869])

In [26]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

# Results in form of Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[55565,  1296],
       [   32,    69]], dtype=int64)