In [13]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
# Importing the datset
dataset = pd.read_csv('creditcard.csv')
x = dataset.iloc[:,1:30].values
y = dataset.iloc[:,30].values

In [15]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 32)

In [16]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

In [18]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

# Results in form of Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[55624,  1226],
       [   17,    95]], dtype=int64)

In [29]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10, n_jobs = -1)
accuracies.mean()

0.9775066312430191

In [30]:
accuracies.std()

0.0011258462419659586

In [11]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs

### Selecting 5 features

In [8]:
# Fitting Feature Selector
sfs1 = sfs(classifier, k_features=5, verbose = 2)
sfs1 = sfs1.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  29 out of  29 | elapsed:    3.1s finished

[2020-04-13 10:11:52] Features: 1/5 -- score: 0.998793039127477[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  28 out of  28 | elapsed:    6.5s finished

[2020-04-13 10:11:59] Features: 2/5 -- score: 0.9988325396651232[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    7.1s finished

[2020-04-13 10:12:06] Features: 3/5 -- score: 0.9988149838706137[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 o

In [8]:
# Showing selected Features
feat_cols1 = list(sfs1.k_feature_idx_)
print(feat_cols1) #[10, 12, 14, 17, 25]

[10, 12, 14, 23, 25]


In [9]:
#Fitting in the model
classifier.fit(x_train[:,feat_cols1],y_train)
y_pred = classifier.predict(x_test[:,feat_cols1])

In [10]:
# Comparing and evaluating results using Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[56842,    19],
       [   53,    48]], dtype=int64)

### Selecting 10 features

In [13]:
# Fitting Feature Selector
sfs1 = sfs(classifier, k_features=10, verbose = 2)
sfs1 = sfs1.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  29 out of  29 | elapsed:    7.4s finished

[2020-04-12 18:11:37] Features: 1/10 -- score: 0.998793039127477[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  28 out of  28 | elapsed:   15.6s finished

[2020-04-12 18:11:52] Features: 2/10 -- score: 0.9988325396651232[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:   17.1s finished

[2020-04-12 18:12:10] Features: 3/10 -- score: 0.9988149838706137[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   

In [14]:
# Showing selected Features
feat_cols2 = list(sfs1.k_feature_idx_)
print(feat_cols2) #[10, 11, 12, 14, 15, 17, 18, 23, 24, 25]

[10, 11, 12, 14, 15, 17, 18, 23, 24, 25]


In [15]:
#Fitting in the models
classifier.fit(x_train[:,feat_cols2],y_train)
y_pred = classifier.predict(x_test[:,feat_cols2])

In [16]:
# Comparing and evaluating results using Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[56761,   100],
       [   22,    79]], dtype=int64)

### Selecting 15 features

In [17]:
# Fitting Feature Selector
sfs1 = sfs(classifier, k_features=15, verbose = 2)
sfs1 = sfs1.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  29 out of  29 | elapsed:    7.2s finished

[2020-04-12 18:19:05] Features: 1/15 -- score: 0.998793039127477[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  28 out of  28 | elapsed:   15.2s finished

[2020-04-12 18:19:21] Features: 2/15 -- score: 0.9988325396651232[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:   16.8s finished

[2020-04-12 18:19:38] Features: 3/15 -- score: 0.9988149838706137[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   

In [18]:
# Showing Features
feat_cols3 = list(sfs1.k_feature_idx_)
print(feat_cols3) # [3, 5, 8, 10, 11, 12, 14, 15, 17, 18, 21, 23, 24, 25, 28]

[3, 5, 8, 10, 11, 12, 14, 15, 17, 18, 21, 23, 24, 25, 28]


In [19]:
#Fitting in the models
classifier.fit(x_train[:,feat_cols3],y_train)
y_pred = classifier.predict(x_test[:,feat_cols3])

In [20]:
# Comparing and evaluating results using Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[56635,   226],
       [   21,    80]], dtype=int64)

### Selecting 20 features

In [7]:
# Fitting Feature Selector
sfs1 = sfs(classifier, k_features=20, verbose = 2)
sfs1 = sfs1.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  29 out of  29 | elapsed:    2.9s finished

[2020-04-12 19:34:54] Features: 1/20 -- score: 0.998793039127477[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  28 out of  28 | elapsed:    6.6s finished

[2020-04-12 19:35:01] Features: 2/20 -- score: 0.9988325396651232[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    6.8s finished

[2020-04-12 19:35:08] Features: 3/20 -- score: 0.9988149838706137[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   

In [21]:
# Showing Features
feat_cols4 = list(sfs1.k_feature_idx_)
print(feat_cols4) # [2, 3, 4, 5, 6, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 24, 25, 28]

[2, 3, 4, 5, 6, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 24, 25, 28]


In [22]:
# Fitting in the models
classifier.fit(x_train[:,feat_cols4],y_train)
y_pred = classifier.predict(x_test[:,feat_cols4])

In [23]:
# Comparing and evaluating results using Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[56353,   508],
       [   14,    87]], dtype=int64)

### Selecting 21 features

In [25]:
# Fitting Feature Selector
sfs1 = sfs(classifier, k_features=21, verbose = 2)
sfs1 = sfs1.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  29 out of  29 | elapsed:    3.0s finished

[2020-04-12 19:18:43] Features: 1/21 -- score: 0.998793039127477[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  28 out of  28 | elapsed:    6.7s finished

[2020-04-12 19:18:49] Features: 2/21 -- score: 0.9988325396651232[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    7.2s finished

[2020-04-12 19:18:57] Features: 3/21 -- score: 0.9988149838706137[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   

In [26]:
# Showing Features
feat_cols5 = list(sfs1.k_feature_idx_)
print(feat_cols5) # [2, 3, 4, 5, 6, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 24, 25, 27, 28]

[2, 3, 4, 5, 6, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 24, 25, 27, 28]


In [27]:
# Fitting in the models
classifier.fit(x_train[:,feat_cols5],y_train)
y_pred = classifier.predict(x_test[:,feat_cols5])

In [28]:
# Comparing and evaluating results using Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[56292,   569],
       [   14,    87]], dtype=int64)

### Selecting 19 features

In [24]:
# Fitting Feature Selector
sfs1 = sfs(classifier, k_features=19, verbose = 2)
sfs1 = sfs1.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  29 out of  29 | elapsed:    2.7s finished

[2020-04-12 19:39:37] Features: 1/19 -- score: 0.998793039127477[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  28 out of  28 | elapsed:    5.6s finished

[2020-04-12 19:39:43] Features: 2/19 -- score: 0.9988325396651232[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    6.5s finished

[2020-04-12 19:39:50] Features: 3/19 -- score: 0.9988149838706137[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   

In [25]:
# Showing Features
feat_cols6 = list(sfs1.k_feature_idx_)
print(feat_cols6) # [2, 3, 4, 5, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 24, 25, 28]

[2, 3, 4, 5, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 24, 25, 28]


In [26]:
# Fitting in the models
classifier.fit(x_train[:,feat_cols6],y_train)
y_pred = classifier.predict(x_test[:,feat_cols6])

In [27]:
# Comparing and evaluating results using Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[56450,   411],
       [   13,    88]], dtype=int64)

In [28]:
# Fitting Feature Selector
sfs1 = sfs(classifier, k_features=18, verbose = 2)
sfs1 = sfs1.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  29 out of  29 | elapsed:    2.6s finished

[2020-04-12 19:42:57] Features: 1/18 -- score: 0.998793039127477[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  28 out of  28 | elapsed:    5.6s finished

[2020-04-12 19:43:03] Features: 2/18 -- score: 0.9988325396651232[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    6.4s finished

[2020-04-12 19:43:09] Features: 3/18 -- score: 0.9988149838706137[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   

In [29]:
# Showing Features
feat_cols7 = list(sfs1.k_feature_idx_)
print(feat_cols7) # [2, 3, 5, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 24, 25, 28]

[2, 3, 5, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 24, 25, 28]


In [19]:
# Fitting in the models
classifier.fit(x_train[:,[2, 3, 5, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 24, 25, 28]],y_train)
y_pred = classifier.predict(x_test[:,[2, 3, 5, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 23, 24, 25, 28]])

In [20]:
# Comparing and evaluating results using Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[56494,   356],
       [   17,    95]], dtype=int64)

In [21]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10, n_jobs = -1)
accuracies.mean()

0.9775066312430191

In [22]:
accuracies.std()

0.0011258462419659586

In [7]:
# Fitting Feature Selector
sfs1 = sfs(classifier, k_features=17, verbose = 2)
sfs1 = sfs1.fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  29 out of  29 | elapsed:    2.7s finished

[2020-04-12 20:07:00] Features: 1/17 -- score: 0.998793039127477[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  28 out of  28 | elapsed:    5.7s finished

[2020-04-12 20:07:06] Features: 2/17 -- score: 0.9988325396651232[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    6.4s finished

[2020-04-12 20:07:13] Features: 3/17 -- score: 0.9988149838706137[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   

In [8]:
# Showing Features
feat_cols8 = list(sfs1.k_feature_idx_)
print(feat_cols8) # [2, 3, 5, 8, 10, 11, 12, 13, 14, 15, 17, 18, 21, 23, 24, 25, 28]

[2, 3, 5, 8, 10, 11, 12, 13, 14, 15, 17, 18, 21, 23, 24, 25, 28]


In [9]:
# Fitting in the models
classifier.fit(x_train[:,feat_cols8],y_train)
y_pred = classifier.predict(x_test[:,feat_cols8])

In [10]:
# Comparing and evaluating results using Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[56553,   308],
       [   14,    87]], dtype=int64)